version: 0.9.2.{build}
image: Visual Studio 2017


environment:
  matrix:
    - PlatformToolset: v141_xp

platform:
    - x64
    - x86

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="x86" set archi=x86
    - if "%platform%"=="x86" set platform_input=x86

    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%
    - nuget restore "%APPVEYOR_BUILD_FOLDER%"\NppMenuSearch\packages.config -PackagesDirectory "%APPVEYOR_BUILD_FOLDER%"\packages

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild NppMenuSearch.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"\NppMenuSearch
    - ps: >-

        if ($env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\$env:PLATFORM_INPUT\$env:CONFIGURATION\NppMenuSearch.dll" -FileName NppMenuSearch.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v141_xp") {
            if($env:PLATFORM_INPUT -eq "x64"){
                $ZipFileName = "NppMenuSearch_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
                7z a $ZipFileName bin\$env:PLATFORM_INPUT\$env:CONFIGURATION\NppMenuSearch.dll
            }
            if($env:PLATFORM_INPUT -eq "x86"){
                $ZipFileName = "NppMenuSearch_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
                7z a $ZipFileName bin\$env:PLATFORM_INPUT\$env:CONFIGURATION\NppMenuSearch.dll
            }
        }

artifacts:
  - path: NppMenuSearch_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v141_xp
        configuration: Release
